In [1]:
!pip install joblib

In [34]:
#Import the the libraries
import os
import matplotlib.pyplot as plt
#save our model using joblib - binary format
import joblib
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")

In [5]:
np.random.randn(3)

array([1.84809498, 1.05742928, 0.4066911 ])

In [7]:
1e-4

0.0001

In [11]:
-np.ones((4,1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [13]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.c_[X,-np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [39]:
z = 34
np.where(z>0, 1, 0)

array(1)

In [62]:
#Create a perceptron class
class Perceptron:
    #data type of eta is float and the default value is None
    def __init__(self, eta:float=None, epochs:int=None):
        #for weight we are going to use the random values
        #1e-4 - 10 to the power of -4
        self.weights = np.random.randn(3)*1e-4
        self.eta = eta #Learning rate
        self.epochs = epochs #iterations
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self,z):
        #Step function as a activation function
        return np.where(z>0, 1, 0)
    
        
    #Fit method
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        #create a bias matrix and concatenate with the X value or X matrix
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print("X with the bias :\n{}".format(X_with_bias))
        
        for epoch in range(self.epochs):
            #Hidden or private method
            print("--"*10)
            print("For epoch >> {}".format(epoch+1))
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            #Act func
            y_hat = self.activation_function(z)
            print("Predicted value after the forward propagation : {}".format(y_hat))
            
            #Calculate error
            self.error = self.y - y_hat
            print("Error at every step :  {}".format(self.error))
            
            #Update the weights after calculate the error values
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
            print("Updated weights after epoch:{} \n {}".format((epoch+1)/(self.epochs),self.weights))
            print("##"*10)
            
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias,self.weights)
        return self.activation_function(z)

In [63]:
OR = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [64]:
def prepare_data(df,target_col = 'y'):
    X = df.drop(target_col,axis=1)
    y = df[target_col]
    return X,y


In [65]:
X,y = prepare_data(df_OR)
ETA = 0.1
EPOCHS = 10
model_or = Perceptron(eta=ETA,epochs=EPOCHS)
model_or.fit(X,y)


X with the bias :
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
For epoch >> 1
--------------------
Predicted value after the forward propagation : [1 1 1 1]
Error at every step :  0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch:0.1 
 [0.00010681 0.00020564 0.09998342]
####################
--------------------
For epoch >> 2
--------------------
Predicted value after the forward propagation : [0 0 0 0]
Error at every step :  0    0
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights after epoch:0.2 
 [ 0.20010681  0.20020564 -0.20001658]
####################
--------------------
For epoch >> 3
--------------------
Predicted value after the forward propagation : [1 1 1 1]
Error at every step :  0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch:0.3 
 [ 0.20010681  0.20020564 -0.10001658]
####################
--------------------
For epoch >> 4
--------------------
Predicted value after th

In [50]:
model_or.predict(X)

array([0, 1, 1, 1])

In [51]:
model_or.predict(X=[[1,1]])

array([1])

In [52]:
model_or.predict(X=[[1,0]])

array([1])

In [53]:
model_or.predict(X=[[0,0]])

array([0])