In [1]:
!pip install joblib

In [2]:
#Import the the libraries
import os
import matplotlib.pyplot as plt
#save our model using joblib - binary format
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [5]:
np.random.randn(3)

array([1.84809498, 1.05742928, 0.4066911 ])

In [7]:
1e-4

0.0001

In [11]:
-np.ones((4,1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [13]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.c_[X,-np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [27]:
#Create a perceptron class
class Perceptron:
    #data type of eta is float and the default value is None
    def __init__(self, eta:float=None, epochs:int=None):
        #for weight we are going to use the random values
        #1e-4 - 10 to the power of -4
        self.weights = np.random.randn(3)*1e-4
        self.eta = eta #Learning rate
        self.epochs = epochs #iterations
        
    #Fit method
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        #create a bias matrix and concatenate with the X value or X matrix
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print("X with the bias :\n{}".format(X_with_bias))

In [28]:
obj = Perceptron(eta=0.01,epochs=10)
obj.eta


0.01

In [29]:
#Initial weights
obj.weights

array([ 6.38115975e-05, -1.96662241e-05,  8.61790749e-05])

In [30]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [32]:
obj.fit(X,y)

X with the bias :
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
